destination: ./.gh-pages/v0.3

# Handling Reading
exclude:
  - Gemfile
  - Gemfile.lock
  - parser
keep_files:
  - parser

# Plugins
plugins:
  - jekyll-redirect-from

# Serving
host: 0.0.0.0
baseurl: /bipuuk/v0.3
