destination: ./.gh-pages

# Handling Reading
exclude:
  - Gemfile
  - Gemfile.lock
  - parser
keep_files:
  - v0.2
  - v0.3
  - parser

# Plugins
plugins:
  - jekyll-redirect-from

# Serving
host: 0.0.0.0
baseurl: /bipuuk
